### ISSUE TITLE
Doesn't work with latest haskell-src-exts

### ISSUE THREAD

**Issue by 23Skidoo** [blitzcode/hackage-diff#5]
When trying to build `hackage-diff` against `haskell-src-exts` 1.19.0 and 1.18.2, I get the following error:

```
Main.hs:593:42: error:
    • Expecting one more argument to ‘Module’
      Expected a type, but ‘Module’ has kind ‘* -> *’
    • In the first argument of ‘Maybe’, namely ‘Module’
      In the type ‘[(String, Maybe Module)]’
      In the type declaration for ‘PackageModuleList’
```

It works with 1.17, though, so the upper bound in the released version on Hackage should be updated.

**Comment by blitzcode** [comment]
It's not meant to, it works with whatever version is in `lts-4.0`. I don't manually maintain version bounds on any of my projects, sorry.

**Comment by 23Skidoo** [comment]
Would you accept a patch adding an upper bound on `haskell-src-exts`?

**Comment by blitzcode** [comment]
Sure, why not, merged your PR!

Sorry my tool isn't in great shape and wasn't immediately helpful to you. Seems like Hoogle 5 will be in 'alpha' for a while and my existing fixes for the changes in the DB format are clearly not sufficient. It might also be a good idea to just remove the `haskell-src-exts` dependency - it's only used in the compare mode where we don't rely on Hoogle. That one was basically an experiment with limited success till I settled on the Hoogle method.
